compute-resource:
  files:
    scheme: sftp
    location: fs0.das5.cs.vu.nl
    path: /home/$CERISE_USERNAME/.cerise

  jobs:
    scheme: slurm
    location: fs0.das5.cs.vu.nl
    # cwl-runner: $CERISE_API_FILES/cerise/cwltiny.py
    cwl-runner: /home/$CERISE_USERNAME/.local/bin/cwltool
    slots-per-node: 4
