compute-resource:
  refresh: 10
  files:
    protocol: sftp
    location: fs0.das5.cs.vu.nl
    path: /home/$CERISE_USERNAME/.cerise

  jobs:
    protocol: ssh
    location: fs0.das5.cs.vu.nl
    scheduler: slurm
    cwl-runner: $CERISE_API_FILES/miniconda/bin/cwltool
    slots-per-node: 4
